name: Trigger FlClash Update
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - FlClash
    tags:
      - "v*"
      
jobs:
  # Send "core-updated" to MetaCubeX/ClashMetaForAndroid to trigger update-dependencies
  trigger-CMFA-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.MAINTAINER_APPID }}
          private-key: ${{ secrets.MAINTAINER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      
      - name: Trigger update-dependencies
        run: |
          curl -X POST https://api.github.com/repos/kafeixiang/FlClash/actions/workflows/update-dependencies.yaml/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            -d '{"ref": "dev-core"}'
